
-- 1. Create Database
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_ASSIGNMENT_DB;

USE DATABASE SNOWFLAKE_ASSIGNMENT_DB;



CREATE SCHEMA IF NOT EXISTS ASSIGNMENT_SCHEMA;

USE SCHEMA ASSIGNMENT_SCHEMA;


-- 3. Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS ASSIGNMENT_WH
    WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- Use the warehouse
USE WAREHOUSE ASSIGNMENT_WH;


-- 4. Create Table
CREATE OR REPLACE TABLE STUDENT_DATA (
    STUDENT_ID INT,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    MARKS INT
);

-- Verify table structure
DESC TABLE STUDENT_DATA;


-- 5. Create Stage
CREATE STAGE IF NOT EXISTS STUDENT_STAGE;

-- Verify stage
SHOW STAGES;


-- 6. Insert sample records
INSERT INTO STUDENT_DATA
    (STUDENT_ID, NAME, DEPARTMENT, MARKS)
VALUES
    (101, 'Rahul', 'CSE', 85),
    (102, 'Priya', 'ECE', 90),
    (103, 'Arjun', 'CSE', 78),
    (104, 'Sneha', 'IT', 88),
    (105, 'Karan', 'MECH', 75);


-- 7. Display inserted records
SELECT *
FROM STUDENT_DATA
ORDER BY STUDENT_ID;


-- 8. INSERT operation
INSERT INTO STUDENT_DATA
    (STUDENT_ID, NAME, DEPARTMENT, MARKS)
VALUES
    (106, 'Ananya', 'CSE', 92);

SELECT *
FROM STUDENT_DATA
ORDER BY STUDENT_ID;


-- 9. UPDATE operation
UPDATE STUDENT_DATA
SET MARKS = 95
WHERE STUDENT_ID = 101;

SELECT *
FROM STUDENT_DATA
WHERE STUDENT_ID = 101;


-- 10. DELETE operation
DELETE FROM STUDENT_DATA
WHERE STUDENT_ID = 106;

SELECT *
FROM STUDENT_DATA
ORDER BY STUDENT_ID;


-- 11. Final verification
SELECT *
FROM STUDENT_DATA
ORDER BY STUDENT_ID;
