


-- 1. Select database and schema
USE DATABASE SNOWFLAKE_ASSIGNMENT_DB;
USE SCHEMA ASSIGNMENT_SCHEMA;


-- 2. Create a table
CREATE OR REPLACE TABLE TIME_TRAVEL_STUDENT (
    STUDENT_ID INT,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    MARKS INT
);


-- 3. Insert sample records
INSERT INTO TIME_TRAVEL_STUDENT
    (STUDENT_ID, NAME, DEPARTMENT, MARKS)
VALUES
    (101, 'Rahul', 'CSE', 85),
    (102, 'Priya', 'ECE', 90),
    (103, 'Arjun', 'CSE', 78),
    (104, 'Sneha', 'IT', 88),
    (105, 'Karan', 'MECH', 75);


-- 4. Display the original data
SELECT *
FROM TIME_TRAVEL_STUDENT
ORDER BY STUDENT_ID;


-- 5. IMPORTANT:
-- Capture the timestamp BEFORE making changes
SELECT CURRENT_TIMESTAMP();




UPDATE TIME_TRAVEL_STUDENT
SET MARKS = 95
WHERE STUDENT_ID = 101;


-- Verify UPDATE
SELECT *
FROM TIME_TRAVEL_STUDENT
ORDER BY STUDENT_ID;



DELETE FROM TIME_TRAVEL_STUDENT
WHERE STUDENT_ID = 103;


-- Verify DELETE
SELECT *
FROM TIME_TRAVEL_STUDENT
ORDER BY STUDENT_ID;




SELECT *
FROM TIME_TRAVEL_STUDENT
AT (TIMESTAMP => 'YOUR_TIMESTAMP_HERE')
ORDER BY STUDENT_ID;
