

-- 1. Select database and schema
USE DATABASE SNOWFLAKE_ASSIGNMENT_DB;
USE SCHEMA ASSIGNMENT_SCHEMA;


-- 2. Create recovery table
CREATE OR REPLACE TABLE RECOVERY_STUDENT (
    STUDENT_ID INT,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    MARKS INT
);


-- 3. Insert sample records
INSERT INTO RECOVERY_STUDENT
    (STUDENT_ID, NAME, DEPARTMENT, MARKS)
VALUES
    (101, 'Rahul', 'CSE', 85),
    (102, 'Priya', 'ECE', 90),
    (103, 'Arjun', 'CSE', 78),
    (104, 'Sneha', 'IT', 88),
    (105, 'Karan', 'MECH', 75);


-- 4. Display original data
SELECT *
FROM RECOVERY_STUDENT
ORDER BY STUDENT_ID;


-- 5. IMPORTANT:
-- Capture the timestamp BEFORE deleting records
SELECT CURRENT_TIMESTAMP();




DELETE FROM RECOVERY_STUDENT
WHERE STUDENT_ID IN (103, 104);


-- Verify deleted records are no longer present
SELECT *
FROM RECOVERY_STUDENT
ORDER BY STUDENT_ID;




SELECT *
FROM RECOVERY_STUDENT
AT (TIMESTAMP => 'YOUR_TIMESTAMP_HERE')
WHERE STUDENT_ID IN (103, 104)
ORDER BY STUDENT_ID;



INSERT INTO RECOVERY_STUDENT
SELECT *
FROM RECOVERY_STUDENT
AT (TIMESTAMP => 'YOUR_TIMESTAMP_HERE')
WHERE STUDENT_ID IN (103, 104);


SELECT *
FROM RECOVERY_STUDENT
ORDER BY STUDENT_ID;


-- 10. Verify total records
SELECT COUNT(*) AS TOTAL_STUDENTS
FROM RECOVERY_STUDENT;
