


SELECT CURRENT_USER();


SELECT CURRENT_ROLE();


SELECT CURRENT_WAREHOUSE();


SELECT CURRENT_DATABASE();


SELECT CURRENT_SCHEMA();


SELECT
    CURRENT_USER()       AS USER_NAME,
    CURRENT_ROLE()       AS ROLE_NAME,
    CURRENT_WAREHOUSE()  AS WAREHOUSE_NAME,
    CURRENT_DATABASE()   AS DATABASE_NAME,
    CURRENT_SCHEMA()     AS SCHEMA_NAME;
